### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by jesse1983** [gabrielguimaraes05/aulasGabriel#1]
Siga os passos abaixo:

1. Abra o cmd/terminal e digite `choco install nvm` 
2. Instale a última versão do node com `nvm install 10`
3. Crie um arquivo na pasta `/issue001` chamado `server.js` e coloque o código abaixo: 
```
console.log('Hello World')
```
4. Execute `node server.js`

**Comment by gabrielguimaraes05** [comment]
feito
